### PR TITLE
Add ARM 32 and 64 cross-build

### PR DESCRIPTION
**Pull request by andrusha**
Enables use on RaspberryPI and similar devices.

Based on https://github.com/ckulka/docker-multi-arch-example

You have to configure build to something like that:

Screenshot 2020-07-07 at 23 55 22

### CODE REVIEW

**Comment by anatolinicolae** [comment]
@andrusha Could you just correctly prefix image tags? I’ll be reviewing this on Monday again, great job so far! 💯👌

**Review by anatolinicolae — CHANGES_REQUESTED** [review]
Needs to have correct docker images prefixes

**Comment by andrusha** [comment]
Updated, after its merged the first build will fail until all architecture images become available

**Review by anatolinicolae — APPROVED** [review]
LGTM

**Pull request merged**
